exp: MinimalPair

mode:
  - evaluate
  - analyze

models:
  hf_causal_model:
    - distilbert/distilgpt2

predfpath: ../cosc426-final/predictions/age_prediction_year.tsv

datafpath: ../cosc426-final/data/age_minimal_pairs_year.tsv

resultsfpath: ../cosc426-final/results/age_results_year.tsv

pred_measure: prob

conditions: age_pair, years

save: by_cond

punctuation: previous

device: cuda:0