exp: MinimalPair

mode:
  - evaluate
  # - analyze # We can't use analyize sine we have multiple minimal pairs for one case

models:
  hf_causal_model:
    - distilbert/distilgpt2

# ********************
# Evaluate & Analyze
# ********************
# assumes below directory structure.
# cosc426
# ├── NLPScholar
# └── cosc426-final
predfpath: ../cosc426-final/predictions/prediction.tsv

datafpath: ../cosc426-final/data/minimal_pairs.tsv

resultsfpath: ../cosc426-final/results/results.tsv

pred_measure: prob

conditions: race, gender, age, offense, severity

save: by_pair, by_cond
