exp: MinimalPair

mode:
  - evaluate
  - analyze

models:
  hf_causal_model:
    - distilbert/distilgpt2

predfpath: ../cosc426-final/predictions/gender_prediction_year.tsv

datafpath: ../cosc426-final/data/gender_minimal_pairs_year.tsv

resultsfpath: ../cosc426-final/results/gender_results_year.tsv

pred_measure: prob

conditions: gender, years, type, severity, template_id

save: by_cond

punctuation: previous

device: cuda