exp: MinimalPair

mode:
  - evaluate
  - analyze

models:
  hf_causal_model:
    - distilbert/distilgpt2

# predfpath: ../cosc426-final/predictions/race_prediction.tsv

# datafpath: ../cosc426-final/data/race_minimal_pairs.tsv

# resultsfpath: ../cosc426-final/results/race_results.tsv

predfpath: ../NLPProject1/cosc426-final/predictions/race_prediction_new_year.tsv

datafpath: ../NLPProject1/cosc426-final/data/race_minimal_pairs_new_year.tsv

resultsfpath: ../NLPProject1/cosc426-final/results/race_results_new_year.tsv

pred_measure: prob

conditions: race, years,template_id,severity,type

save: by_cond

punctuation: previous

device: cuda:0