exp: MinimalPair

mode:
  - evaluate
  - analyze

models:
    hf_masked_model:
      - distilbert-base-uncased
      - FacebookAI/roberta-base


predfpath: ../cosc426-final/predictions/race_prediction_new_year.tsv

datafpath: ../cosc426-final/data/race_minimal_pairs_new_year.tsv

resultsfpath: ../cosc426-final/results/race_results_new_year.tsv

# predfpath: ../NLPProject1/cosc426-final/predictions/race_prediction_new_year.tsv

# datafpath: ../NLPProject1/cosc426-final/data/race_minimal_pairs_new_year.tsv

# resultsfpath: ../NLPProject1/cosc426-final/results/race_results_new_year.tsv

pred_measure: prob

conditions:  race,punishment,severity

save: by_cond

punctuation: previous

device: cuda:0