exp: MinimalPair

mode:
  - evaluate
  - analyze

models:
  hf_causal_model:
    - distilbert/distilgpt2

predfpath: ../cosc426-final/predictions/race_prediction_year.tsv

datafpath: ../cosc426-final/data/race_minimal_pairs_year.tsv

resultsfpath: ../cosc426-final/results/race_results_year.tsv

# predfpath: ../NLPProject1/cosc426-final/predictions/race_prediction_year.tsv

# datafpath: ../NLPProject1/cosc426-final/data/race_minimal_pairs_year.tsv

# resultsfpath: ../NLPProject1/cosc426-final/results/race_results_year.tsv

pred_measure: prob

conditions: race, years

save: by_cond

punctuation: previous

device: cuda:0